added rockets
trowl223/Compound_X pull request #153
Opened 2017-09-05 19:23 UTC by bleehu

big bada boom

2017-09-05 19:34 UTC, 1sourcecontrol requested changes
Left one comment, otherwise, looks good!

2017-09-05 19:34 UTC, 1sourcecontrol commented on play/PlayerRules/CharacterCreation/04_01_Weapons.txt
> +        Airburst Cluster Missile, 100 explosive damage.
Don't need to restate the damage

2017-09-05 19:46 UTC, bleehu commented on play/PlayerRules/CharacterCreation/04_01_Weapons.txt
> +        Airburst Cluster Missile, 100 explosive damage.
change made

2017-09-13 20:49 UTC, 1sourcecontrol commented
Sorry for the delay, I'm going to probably take your rocket changes and incorporate them into my weapon branch before I merge into the super branch. I didn't realize James had merged his weapon changes into my weapon branch (instead of the super branch). And I want to minimize the conflicts.

2017-09-13 21:06 UTC, bleehu commented
So close this and PR to your weapon branch?

2017-09-13 21:21 UTC, 1sourcecontrol commented
It'll be much easier to do it myself than dealing with conflicts

2017-09-17 04:06 UTC, 1sourcecontrol commented
Added shotguns to my combat branch with turtle's other weapons. Feel free to close this branch. (i'm not sure if it's taboo to close someone else's branch in progress, that's why i'm not closing yours)

2017-09-18 17:04 UTC, closed without merging