stylized melee weapons to make it easy to read to update Pigeon's cha…
trowl223/Compound_X pull request #307
Opened 2018-01-19 23:49 UTC by bleehu

…racter

2018-01-22 01:41 UTC, Turtlelord26 requested changes
Many section and subsection headers missing whitespace, not sure if parser handles gracefully.

One more note about blanks after chapters but at this point I may be fighting a losing battle.

I would make Unarmed Fighting and Pistols into chapter headings. Particularly for pistols I see consecutive section headings as questionable style.

Inconsistent spacing in many locations in Definition lists, including lack of space after the colon in some cases. After seeing edits to other weapon pages standardizing those I will bring it up here.

Some grenades have not had their descriptions line length limited.

2018-01-22 01:41 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Hand-to-Hand [Trained]==
Unambiguously could use a blank line after this subsection heading for readability.

2018-01-22 01:41 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
>  (10 skill in Melee Combat or Unarmed Combat)
How will this line parse?
Maybe could remove the () and give it a "Prerequisites: " to join it to the rest of the definition list.

2018-01-22 17:23 UTC, bleehu commented
Great catches! Thanks for the review! 

What do you think of this?

2018-01-22 18:46 UTC, Turtlelord26 requested changes
Remaining spacing issues marked. Remaining line length issues noted.

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Hand-to-Hand [Expert]==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 1 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Eliazar Plasma Torch$240==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Gurbur G1 Combat Knife$315==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Gurber GS101 Combat Sword$680==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 5 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +== Guri Grabber Knife$470==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Guri Carbon Whip$560==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==SPECO SP10 VAE Combat Knife$640==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==SPECO SPC50 VAE Circular Saw$695==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==SPECO SP30 VAE Combat Sword$1245==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 10 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Eliazar E500 Assisted-Sledgehammer$811==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Eliazar E5500 Power Fist$880==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Muzashi VAE Katana$1354==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +==Eliazar Plasma Sword$987==
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 1 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 5 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +=====LEVEL 10 REQUIREMENT WEAPONS=====
Mark

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
>  Only legs and torso (2*45 damage)+1xBleed within a 5m radius. At least one hit must damage health to cause  Bleed.
Line Length

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
>  Only legs and torso (2*50 damage)+1xBleed within a 6m radius. At least one hit must damage health to cause Bleed.
Line Length

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
>  All Poison Damage is negated by use of a gas mask.
Line Length

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +	2x inner blast radius when indoors. 120 explosive damage within a 2m radius, 60 explosive within a 5m radius.
Line Length

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
> +Only legs and torso (2*60 damage)+1xPlasma Burn within a 5m radius. At least one hit must damage health to cause Plasma Burn.
Line Length

2018-01-22 18:46 UTC, Turtlelord26 commented on CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
>  attempt to break the blindness with a perception check at 85% (disregarding bonuses). If the grenade
Line Length

2018-02-01 23:17 UTC, bleehu commented
Ouch. Cut me bleeding. Red all over. 

How's that now?

2018-02-12 21:05 UTC, Turtlelord26 commented
Much better but I'm feeling perfectionistish at the moment. Watch this space.

2018-02-12 22:48 UTC, Turtlelord26 approved these changes

2018-02-12 22:48 UTC, merged