Mh issue 353 engi dmg type
trowl223/Compound_X pull request #358
Opened 2018-03-07 19:55 UTC by bleehu

The most dramatic change here isn't that I added very specific damage types (most of which could have been easily and correctly inferred) to the Engineer Processes, but that in doing so, I felt compelled to add the damage types to the basic rules explicitly as well. 

I also added a new damage type, which I felt was necessary to capture the flavor of what the Engineer's processes were doing. Internal Damage. Which is very much subject to comment/review/dismissal.

2018-03-07 20:01 UTC, bleehu commented
This should address Issue #353. Mentioning it purely for the git tracking.

2018-03-07 21:21 UTC, Turtlelord26 requested changes
I like damage types, but I also want to avoid damage type creep. To that end, I want to see each damage type we make have a mechanical and/or flavorful (both preferred) reason for existing.

My analysis by item:

Electric: An excellent type. It's mechanical and flavor purposes are the same: to specifically threaten (semi)mechanical characters and other electronic systems.

Fire: Good, but maybe can improve. A necessary type to have to describe certain environmental effects, and helps us give resistance to that class of ow to particular races. Also flamethrowers.
However, since we don't seem to be baking anything special into the damage type intrinsically, I would like us to consider rebranding it to Thermal Damage, and packing extreme cold effects under the same umbrella. If we're remanding burning effects to individual weapon descriptions, we can do the same for numbness inducement, frostbite, etc, and heat resistant equipment is also usually effective against cold environments too (with the exception of truly extreme conditions).

Acid: Excellent. The flavor of pH damage hard to capture with another type, and this type mechanically supports specifically attacking many items, objects, and structures. As noted here, shares a potential similarity with Fire/Thermal by inducing DoTs, but this is acceptable because, at least flavorly, the DoTs will require very different treatment to remove.

Internal: Seems like a handy catch-all for damage that bypasses all defenses. Here's a throwaway concern: Sith Lightning in SWtoR deals internal damage. Electrical surges are modelable by an internal damage type. This is only saved from redundancy by our Electrical damage having special race-based effects, which we would not want to manually include on every electrical effect in the game.
Here's the real concern I have. If Internal's mechanical niche is that it bypasses defenses, then Internal and Explosive are badly redundant. One of them needs to go, and I think I like Internal more, since it can describe more things. My first instinct for modifying frag grenades, rocket launchers, etc. to account for losing their damage type would be to split the damage into a small chunk of Internal or Blunt (representing the shockwave) and a large chunk of Ballistic (the shrapnel), which could be blocked by armor. My logic is that I'm not confident that shrapnel and buckshot are different enough to warrant a different damage type.
Intended as discussion points.

Sidenote: I'm really not sure about blunt, and would like to see it also folded into Internal. That might even be within the scope of this PR.

Oh, and adding the damage types to the Engineer processes is good and helpful. I agree with your selections.

Merge blocked by discussion points under Fire and Internal, not by specific change requests at this time.

2018-03-07 21:37 UTC, bleehu commented
Serves me right for scope creep. The change I was asked to make is blocked by the changes I wasn't. And half of these would have been let through if I'd broken 'em up into small changes. Still catching up on reading.

2018-03-07 21:46 UTC, bleehu commented
If we lose either explosive or internal damage, what happens to the EOD heavy armor that reduces nearby explosive damage, but shouldn't reduce hacked medical microbots that feast upon thy innards?

2018-03-07 21:48 UTC, bleehu commented
Similarly, if we collapse fire damage and ice damage into thermal damage, how do we model thermal damage to electronic targets? Machines fare quite well in the cold, but tend to be inhibited by their resisters melting.

2018-03-08 00:34 UTC, Turtlelord26 commented
Re EOD heavy armor: my point becomes less applicable if explosive damage does not in fact bypass defenses. If we intend to have especially shrapnel-resistant armors then we probably shouldn't collapse explosive.

What do you think about folding blunt into internal though?


Re Thermal: I'm not at this time anticipating any Cold damage weapons (even if we did have a cold grenade, the temperature shock happens fast enough I think we can justify the damage to mechanicals). So the primary instances where you'd see Thermal (cold) damage would be environmental. In those cases, we would model the different tolerance of robots to cold by specifying that they don't take damage until much lower temperatures than the average humanoid starts hurting at.

2018-03-08 07:26 UTC, bleehu commented
I'm willing to entertain the idea of folding fire damage and cold damage into Thermal Damage; you've made a pretty good argument. But I'm gonna call 'scope creep' because if we want to change the places where fire damage already exists (including several dungeon repos) that's going to take a whole 'nother round of work.

2018-03-08 07:29 UTC, bleehu commented
added Issue #361 to track the work.

2018-03-08 07:44 UTC, Turtlelord26 commented
Added #362 for the other point to allow merge of current work.

2018-03-08 07:44 UTC, Turtlelord26 approved these changes

2018-03-08 17:37 UTC, merged