Added Reflex Save to grenades
trowl223/Compound_X pull request #523
Opened 2018-06-12 22:07 UTC by bleehu

moved Reflex Modifier to stat block of grenades and added a reflex save to all grenades
Issue #505 
	modified:   Items/04_01_Melee_&_Thrown_Weapons.txt

2018-06-13 04:21 UTC, Turtlelord26 requested changes
We need to specify what making (and failing) the reflex save means for each grenade.

2018-06-13 23:22 UTC, Turtlelord26 requested changes
At ground zero of the 10m cloud grenades, making the reflex save lets you dive 5m. That's a long way. Not sure if flavor compatible. 
What if instead the reward for making the save is diving prone behind cover (relative to ground zero), *if such cover is available nearby*, and otherwise hunkering in place to take somewhat reduced damage?
At the risk of complexity, we could also allow diving onto the grenade to provide everyone around you cover at the cost of massively increased ouch.

2018-06-14 16:26 UTC, bleehu commented
I think it's fairly intuitive to add some complexity at this point. I'll do that.

Diving on a grenade sounds like maybe a feat? Call it "courage" or something? What do you think? That way we spread the complexity around a bit

2018-06-14 16:59 UTC, Turtlelord26 commented
I'm not confident that a feat for diving onto grenades would ever be taken over other feats less likely to kill people's characters. If it was a feat I recommend it be stapled to another effect, and secondary to it.

2018-06-19 18:03 UTC, dfuchs2 approved these changes
I like it. It's good to remove the potential for movement exploits.

2018-06-19 20:34 UTC, Turtlelord26 approved these changes

2018-06-19 20:43 UTC, merged