Procedural Dungeon Generator
trowl223/Compound_X pull request #551
Opened 2018-06-21 22:05 UTC by dfuchs2

2018-06-21 22:07 UTC, dfuchs2 commented
I'm looking for some advice for what to add. I feel like it isn't complete yet, but I can't decide what I want to add to it.

2018-06-22 05:19 UTC, Turtlelord26 commented
Do you still want reviews? @dfuchs2

2018-06-22 19:32 UTC, bleehu requested changes
Can we re-post this article in the Dungeon Master's guide instead of in the middle of the player's handbook? https://github.com/bleehu/CX_Galaxy_Masters_Guide/tree/master/3_Making_Dungeons

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +well as any area-specific rules that may apply.
Starting with a planet type is a specific implementation of the more abstract strategy of starting with a theme or idea. A lot of good maps are made by starting with an idea, such as "what if we did a map that was on a living, moving tree? Wouldn't that be cool?" 
Instead, I recommend that your first step in creating a dungeon be setting a goal. How will you know when your dungeon is finished? Dungeoneering is an inherently iterative and recursive process. If you don't set a termination point at the start, then you'll be working on your dungeon forever, and nobody will ever get to see your hard work. Suggested goals are things like "I want this dungeon to be fun for every type of player in Bartle's Taxonomy." Another good list of goals are in the dungeon festival rubric.

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +story, it's usually a good idea for your characters to have some kind of backstory, whether it's
Story sense is a must-have, not an optional thing for a decent dungeon. If you can't roll investigate at some point in your dungeon to find out something interesting, then you've failed your explorer player types and you've undervalued that particular skill. You've made a chess board, not a dungeon.

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +their footprints. The hunter class might be very useful in a situation such as this, because
What you're driving at here is that a good dungeon has something for every class to excel at. We should say that at some point.

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +anybody else might be forced to stay inside or be hindered by the air quality outside.
Volcanic wasteland would be a super cool battlefield! Great idea!

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +players must have fun and that the game be interesting.
You are absolutely right about this! Fun and/or interesting is the most important thing! :+1:

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +
... Where do you talk about loot? You hint at puzzles a couple of times, but don't really explicitly call them out. https://www.youtube.com/watch?v=XWgc20zbRXk&list=PLDPL7seU9mMcBZ8yonxZvyEcFHg8dy1wl

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +melting, explosive poison gas, then it's your job to determine exactly how it works.
"light-activated, face-melting, explosive poison gas" :joy: This is just jexcellent! Well said!

2018-06-22 19:32 UTC, bleehu commented on Procedural Dungeon Generator
> +rule of thumb, it's a good idea to make combat fast-paced, tactical, and enjoyable for everybody.
We should maybe call out specifically that enemies might not use the feats, items or abilities available to the players. It's a common mistake that first-time GMs or Dungeoneers often make. Also, while turns in combat should be quick to keep player's interest, it's ok to vary the pacing during the course of the dungeon to vary the interest curve. https://github.com/bleehu/CX_Design_Guide/blob/master/DevProcesses/welcome.md#interest-curves

2018-06-25 00:23 UTC, closed without merging

2020-04-07 16:59 UTC, Turtlelord26 commented
@bleehu @dfuchs2 Is this branch safe to delete?