added dog toy item
trowl223/Compound_X pull request #585
Opened 2018-06-28 22:07 UTC by bleehu

For the shenanigans

2018-06-29 23:51 UTC, rosebrallier requested changes
Toys are often aimed more towards play and enrichment purposes than for in-the-moment attention control. "Getting or directing a trained animal's attention" implies that the toy's primary purpose is to control the doge.

2018-07-15 22:08 UTC, rosebrallier approved these changes

2018-07-15 22:08 UTC, rosebrallier commented
Shipit!

2018-07-15 23:06 UTC, Turtlelord26 approved these changes

2018-07-16 01:40 UTC, merged