added dog collar/leash
trowl223/Compound_X pull request #586
Opened 2018-06-28 22:17 UTC by bleehu

added collar and leash item.

2018-06-29 23:44 UTC, rosebrallier requested changes
Substitute a more reasonable collar width or swap to a harness altogether for realism and husbandry purposes.

2018-06-29 23:44 UTC, rosebrallier commented on Items/07_Items.txt
> +    This 30cm wide collar comes with up to 18 characters of monogram and a micro
The width of a collar usually refers to the distance across the collar, not the length around; 30cm is really wide compared to the length of most dogs' necks.
In addition, current husbandry standards greatly favor harnesses over collars; harnesses don't choke a dog or cause spinal injuries when pressure is put on them.

2018-06-30 23:26 UTC, bleehu commented on Items/07_Items.txt
> +    This 30cm wide collar comes with up to 18 characters of monogram and a micro
Will change!

2018-07-02 05:53 UTC, rosebrallier approved these changes
Wooooooo!

2018-07-02 05:53 UTC, rosebrallier commented on Items/07_Items.txt
>  chip that helps you find your dog if it runs away. The collar itself is
Missed a reference to collar. Nb.

2018-07-15 21:59 UTC, merged