Constructor Drone Second Trait
trowl223/Compound_X pull request #626
Opened 2018-08-01 19:13 UTC by dfuchs2

2018-08-01 19:46 UTC, bleehu requested changes
This is really good, but a bit OP. I think the obvious synergy between Construction bot as a species and engineer as a class has been telegraphed well by their names. But we'll need to nerf the bonus and/or spread the benefit around a bit because this turns into like a 30-something jury rigging at level 1, which is higher than we want.

2018-08-01 19:46 UTC, bleehu commented on CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
> +to building. Gain Jury-Rigging at 15 if you take it as a level 1 skill, or at 20 if you
15 and 20 are a little too high for level 1 with @rosebrallier's new skill system, where 6 or 12 would be the max expected of a level 1 character. Also, Engineers already get a flat bonus of 10 to Jury-rigging as well as proficiency in the skill. I really like the idea that construction bots are better at learning to build things, so I hope we keep the theme. I really like it. Rev suggests changing this to advantage on jury-rigging instead?

2018-08-01 20:59 UTC, Turtlelord26 reviewed
This one also looks like two traits. Most of the traits currently in place are fairly narrow, which allows more customization when building characters.

I would suggest (again) to address blee's first concern by swapping out the flat bonuses to Advantage rolls. Advantage is pretty good tech because it's less powerful than +20 but feels so much cooler. Advantage will also be more powerful in the late game because, unlike giving a bunch of points in jury-rig at level 1, it won't count against the 60 skill point cap.

2018-08-16 23:37 UTC, bleehu approved these changes
Shipit!

2018-08-16 23:46 UTC, merged

2018-08-16 23:55 UTC, bleehu commented
Linking Issue #555