added flavor text to conditions
trowl223/Compound_X pull request #679
Opened 2018-09-15 21:33 UTC by bleehu

and changed descriptions to full sentences in the third person.

	modified:   01_05_Conditions.txt

2018-09-15 22:25 UTC, Turtlelord26 requested changes
🐢s like turning old, sad rules into new, happy, proseful rules!

Please do not be alarmed by the 19 inline notes below.

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +characters as well who can leak coolant and lubricant.
Sentence structure: "This can happen to both..." but only one predicate subject noun.
And: Starting a sentence with a conjunction.
I think the "blood. But" may have been meant to be "blood, but"

Sp: Contain, up in line 8.

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +damage once per round at the beggening of their turn. Broken with Medicine Skill
sp: beginning

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +check. The Save DC to stop varies; the cause of the bleed effect should list it
Request better flow than "Broken with Medicine Skill check."

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +    A Character that is bleeding takes d10/2+1 (drop the remainder) stackable
Intentional balance change from the current 1d10?

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +    A Burning character takes 2d10 damage per round at the beggeining of their
sp: beginning

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +turn. Most burning can be extinguished by dousing a character in a non-flamable
"...turn[, per stack]"?

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +intensifies by one stack.
degree is a loaded word when talking about burns. Since our stacks don't really correspond to first, second, and third degree burns, we may want a different word here.

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +    Some burning chemicals, like white phosphorous or most napalms contain the
gr: comma following 'napalms' to end the appositive.

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +means, such as the Doctor's Purge ability.
Or removing the combusting material? Stealth buff to species that wear clothes and/or classes that wear armor?

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +signal jamming, malware or sometimes direct electrical interfereance. When this
sp: interference

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +certain, agonizing death. Though there are certainly other scary things in the
gr: "death, though"

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +Will Save.
Rate limit?

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +to defeat fear. DC 75, Will save.
Rate limit again

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +until they pass a Will saving throw at DC of 70, whichever is quicker.
Rate limit.

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +have the tendancy to stick to a target and their armor, continuing to do damage
sp: tendency

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +is addative, any given set of armor cannot have its APL reduced by more than
sp: additive

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +    A Character that is afflicted with poison takes a d10 internal damage per
templating: 1d10, removing "a"

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +Round at the beggining of their turn.
sp: beginning

2018-09-15 22:25 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +Character blacks out and is now Downed, but not Bleeding Out. As long as a
We have an Unconscious condition for Downed-But-Not-Bleeding-Out, don't we?

2018-09-15 23:21 UTC, bleehu commented on 01_05_Conditions.txt
> +    A Character that is bleeding takes d10/2+1 (drop the remainder) stackable
No change; see line 7 in the dev branch.

2018-09-15 23:22 UTC, bleehu commented on 01_05_Conditions.txt
> +Character blacks out and is now Downed, but not Bleeding Out. As long as a
Link me to it in dev

2018-09-16 05:57 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +    A Character that is bleeding takes d10/2+1 (drop the remainder) stackable
Fair enough, I guess we've just been playing it wrongly.

2018-09-16 06:00 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +Character blacks out and is now Downed, but not Bleeding Out. As long as a
5 references in combat rules, 4 written by me and 1 by 1source, are all I can find.
Can we make an official unconscious condition? (New issue)

2018-09-16 06:00 UTC, rosebrallier approved these changes
This is a monumental effort!!! Thank you so much!
Spelling and grammar notes, tone and style suggestions, and a few errant "Fort Saves"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +characters as well who can leak coolant and lubricant.
suggestion: "leak blood, and to cybernetic targets, who can leak coolant and lubricant."

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +check. The Save DC to stop varies; the cause of the bleed effect should list it
suggestion: "Bleeding is stopped with a Medicine..." (or staunched, or removed, or almost anything but "broken")

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +check. The Save DC to stop varies; the cause of the bleed effect should list it
"Medicine DC" (it's a skill check, not a save)

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    A Character that is Fronzen takes d10 damage per round at the beggining of
sp "Frozen"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +or with Dexterity(Medicine) Skill check, DC 50.
"Medicine (Dex)"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +away form the source of fear, or taking an action to roll to defeat fear. DC 50,
sp: "from"
I'd use "moving" over "running": people can't really run in zero-g for example, and under water it'd probably be more effective to swim away.

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +-5 to skill rolls.
gr: the "they" here has no direct reference. either move this sentence back up into the prev. paragraph, or swap subjects from "they" to "characters"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    A Character aflicted with Necrosis takes 2d10 +5 damage per turn. If left
specify whether damage happens at the beginning or end of turn

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +75, must be rolled to cure it, usually by surgically removing the dead tissue
gr: "A Medicine check of DC 75 must be rolled"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +until they pass a Will saving throw at DC of 70, whichever is quicker.
I think the more common phrasing is "a DC 70 Will Save"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +Burn Token per round at the beggening of their turn. Each "token" lasts for 2
sp: "beginning"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    If the targets armor is hit/pierced, the armor's AP Level is reduced by 1,
imo either fully abbreviate APL or spell it out fully.

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
>  these drinks, the effect should list a FORT save to avoid increasing your level
sc: We...don't have Fort saves.
"your level" needs fixing

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    While buzzed, a Character gains a +1 to miss with any attack and a temporary
sc: do we swap to "-1 accuracy" while we're here?

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +-1 to Perception. At the same time, the Character gets a +1 to charisma and luck.
caps: "Charisma and Luck"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +You also take a -20 to skill checks involving driving, flying or operating heavy
I like to explicitly say "take a penalty of -20"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +machinery. If the Character fails a Fort save to prevent increasing their
Fort saves don't exist

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +Hammered, being Buzzed will wear off in two hours.
You can delete "being" if you want

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +The Character takes a temporary -2 to dex, perception and charisma. If the
caps: "Dexterity, Perception and Charisma"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +Character blacks out and is now Downed, but not Bleeding Out. As long as a
I _swear_ I wrote Unconscious at some point. Apparently I just thought about it...

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    A Stunned or Paralyzed target cannot take actions for the duration of their
"the Condition"

2018-09-16 06:00 UTC, rosebrallier commented on 01_05_Conditions.txt
> +Character blacks out and is now Downed, but not Bleeding Out. As long as a
-facepalm- I found where I wrote it. It's in my Starfall files. Lemme just...sneakily PR this... (herp derp derp)

2018-09-16 19:12 UTC, bleehu commented on 01_05_Conditions.txt
> +check. The Save DC to stop varies; the cause of the bleed effect should list it
oooh! I relish the chance to use good word choice like "staunched" !

2018-09-16 19:12 UTC, bleehu commented on 01_05_Conditions.txt
> +check. The Save DC to stop varies; the cause of the bleed effect should list it
great suggestion!

2018-09-16 19:23 UTC, bleehu commented on 01_05_Conditions.txt
> +or with Dexterity(Medicine) Skill check, DC 50.
I was wondering about that...

2018-09-16 19:24 UTC, bleehu commented on 01_05_Conditions.txt
> +away form the source of fear, or taking an action to roll to defeat fear. DC 50,
great catch!

2018-09-16 19:31 UTC, bleehu commented on 01_05_Conditions.txt
>  these drinks, the effect should list a FORT save to avoid increasing your level
It doesn't really make sense to make it a Shock Save, a raw Fortitude roll is the closest thing we have to holding one's liquor. unrelated, I think it's also the closest thing we have to being able to hold one's footing.

2018-09-16 19:35 UTC, Turtlelord26 commented on 01_05_Conditions.txt
>  these drinks, the effect should list a FORT save to avoid increasing your level
Rabbit holing, but I seem to recall you mentioning you wanted to use Shock for maintaining footing when we were reviewing carbine expertise?

2018-09-16 21:12 UTC, rosebrallier commented on 01_05_Conditions.txt
>  these drinks, the effect should list a FORT save to avoid increasing your level
If it's a raw fort check, then it's a "Fort check/roll", not a Save, because Fort is not a Save.

2018-11-01 02:23 UTC, rosebrallier approved these changes
Ship-it pending spelling notes, Turtle's request, and the "Fort save" issue.

2018-11-01 02:23 UTC, rosebrallier commented on 01_05_Conditions.txt
> +beggining of their turn. If left unhealed for more than a day, the infection
sp: beginning

2018-11-01 02:23 UTC, rosebrallier commented on 01_05_Conditions.txt
> +from burn tokens is addative, any given set of armor cannot have its APL reduced
sp: additive

2018-11-01 02:25 UTC, rosebrallier commented on 01_05_Conditions.txt
> +    A Lonely Character moves 1m slower every two Actions (round down) and take a
*takes

2018-11-03 22:49 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +turn. Most burning can be extinguished by dousing a character in a non-flamable
Was it per stack or was the stack only meant as a timekeeping device?

2018-11-03 22:49 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +intensifies by one stack.
Unresolved query.

2018-11-03 22:50 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +means, such as the Doctor's Purge ability.
not silly.

2018-11-03 23:01 UTC, bleehu commented on 01_05_Conditions.txt
> +turn. Most burning can be extinguished by dousing a character in a non-flamable
more fire meant more damage.

2018-11-04 22:59 UTC, bleehu reviewed
resolved comments changed in last push.

2018-11-04 22:59 UTC, bleehu commented on 01_05_Conditions.txt
> +means, such as the Doctor's Purge ability.
I don't understand the action item here.

2018-11-04 22:59 UTC, bleehu commented on 01_05_Conditions.txt
> +Will Save.
I think since will averages around +16, having a better than even chance of not shaking it off every action means your chances of having shaken off the effect after n actions asymptotically approaches 0 as n increases, we'll be ok with this one.

2018-11-04 23:11 UTC, Turtlelord26 commented on 01_05_Conditions.txt
> +turn. Most burning can be extinguished by dousing a character in a non-flamable
We need to say so then.

2018-11-04 23:15 UTC, bleehu commented on 01_05_Conditions.txt
> +turn. Most burning can be extinguished by dousing a character in a non-flamable
Added saying so.

2018-11-04 23:17 UTC, Turtlelord26 approved these changes

2018-11-04 23:18 UTC, merged