Adding: Capacitor Regulator
trowl223/Compound_X pull request #710
Opened 2018-11-04 07:03 UTC by Masterdiekillsu

Adds an attachment for laser guns to increase mag size on a universal level.

2018-11-04 07:08 UTC, Turtlelord26 reviewed
🐢 is pondering this flavor and will get back to you soon.

2018-11-04 07:10 UTC, Turtlelord26 commented
By the way, the PR is based from RC,  and should probably be rebased to dev.

2018-11-04 07:12 UTC, bleehu requested changes
I like the concept! Some spelling and grammar fixes, and I think we should halve the price or so. Once the grammar is fixed, I'll approve it.

2018-11-04 07:12 UTC, bleehu commented on Items/04_00_WeaponAttachments.txt
> +== Capacitor Rgulator $1500 ==
SP: "Regulator"

2018-11-04 07:12 UTC, bleehu commented on Items/04_00_WeaponAttachments.txt
> +   An addition to a laser gun that helps conserve power usage of the guns battery
apostrophe: "to the gun's battery"

2018-11-04 07:12 UTC, bleehu commented on Items/04_00_WeaponAttachments.txt
> +spreading out the discgarge of energy in a single blast to higher accurate levels,
sp: discharge

2018-11-04 07:12 UTC, bleehu commented on Items/04_00_WeaponAttachments.txt
> +spreading out the discgarge of energy in a single blast to higher accurate levels,
grammar: "to _more_ accurate levels"

2018-11-04 07:26 UTC, Masterdiekillsu commented on Items/04_00_WeaponAttachments.txt
> +== Capacitor Rgulator $1500 ==
lol! Thank you, also do you want me to base this out of dev instead of R_C?

2018-11-04 09:21 UTC, bleehu commented on Items/04_00_WeaponAttachments.txt
> +== Capacitor Rgulator $1500 ==
oh geeze. Yes please.

2018-11-04 22:49 UTC, bleehu commented
Also, don't forget to link the issue that this would solve!

2018-11-08 18:56 UTC, Turtlelord26 reviewed
🐢 is not the largest fan of this flavor. I see the argument for an effective capacity increase by increasing the efficiency of the internal power train, but I don't think I can buy that there's enough inefficiency in a top-of-the-line Rigistruct or ECSC rifle to have an effect. Would you consider instead an attachment that manages to capture waste heat from firings and convert it back into capacitor charge? Probably makes the weapon less wieldy (reducing reflex). The difference is that it increases efficiency after the shot instead of before it.

2019-06-13 03:23 UTC, bleehu commented
This is stale and the dev has left the team. I'm killing it.

2019-06-13 03:23 UTC, closed without merging