Medicalize Steady Shot
trowl223/Compound_X pull request #736
Opened 2018-12-08 08:32 UTC by Turtlelord26

Slight functional change in that you can use Steady Shot and then Aim, but it made the wording a lot cleaner I think.

2018-12-09 22:22 UTC, bleehu requested changes

2018-12-09 22:22 UTC, bleehu commented on CharacterCreation/03_Feats.txt
> +	Steady Shot may be taken multiple times, up to a maximum of 4; the bonuses stack.
blocker: need more info! Can I take this feat 4 times and spend one Action to get a +4 to accuracy and shoot dudes who are hunkered? I think this might break!

2018-12-10 06:46 UTC, Turtlelord26 commented on CharacterCreation/03_Feats.txt
> +	Steady Shot may be taken multiple times, up to a maximum of 4; the bonuses stack.
Calling scope creep as the stackability was already in the feat and removing it is a big structural change.

2018-12-10 16:13 UTC, bleehu approved these changes
:shipit:

2018-12-10 16:13 UTC, bleehu commented on CharacterCreation/03_Feats.txt
> +	Steady Shot may be taken multiple times, up to a maximum of 4; the bonuses stack.
Raising another issue.

2018-12-10 18:09 UTC, merged