Added Adrenaline Syringe
trowl223/Compound_X pull request #860
Opened 2019-05-01 01:27 UTC by bleehu

modified:   07_Items.txt

2019-05-01 07:31 UTC, Turtlelord26 requested changes
NB: It feels more expensive than 18, probably in part due to the flavor
> the device measures out the appropriate dosage automatically

I don't see any obvious mechanical or balance issues with such an item existing, and from a level design perspective it adds a cool small-loot option. 👍 

Flavor police incoming: Does the adrenaline work on Security Drones too? How about Kurish? Approval pending this flavor point discussion only.

2019-05-01 07:31 UTC, Turtlelord26 commented on Items/07_Items.txt
> +or stabalize them. The character's Death Saving Throws are all reset as if that
Sp: stabilize

2019-05-01 16:35 UTC, bleehu commented
Line 138 specifically says organic character, so no Security Drones. Kurish is up for debate.

2019-05-01 16:45 UTC, Turtlelord26 commented
My bad.

2019-05-01 16:46 UTC, Turtlelord26 approved these changes

2019-05-01 16:59 UTC, Turtlelord26 commented
We can decide later if realism or gameplay is more important re having a different adrenaline for each species. I have a hunch which way that has to go.

2019-05-14 20:34 UTC, rosebrallier approved these changes
I like it! Ship pending spelling fixes.

2019-05-16 03:37 UTC, merged