clarified healing rules and changed to 3 actions
trowl223/Compound_X pull request #875
Opened 2019-06-13 05:50 UTC by bleehu

modified:   01_01_Basic_Rules.txt
	modified:   Combat Rules/1_Combat_Rules.txt
	modified:   Items/07_Items.txt

should address issue #673

2019-06-13 05:51 UTC, bleehu commented
I think it's an important balance change to make healing a wound take longer than aiming and firing a gun. It radically changes our action economy. With this significant nerf to med kits and repair kits, we may consider dropping the price for them.

2019-06-13 06:52 UTC, Turtlelord26 requested changes
I am not opposed to testing out slow-heal. I have been thinking about nerfing the amount of each heal, but slowing them down has much the same effect and is certainly worth investigating.
EDIT: Also, the flavor of your way is better. 🐢 

Before greenlighting, I will ask you to additionally apply this nerf to relevant Doc and Engi abilities. I see class balance suffering a lot otherwise.

2019-06-13 06:52 UTC, Turtlelord26 commented on 01_01_Basic_Rules.txt
> +treating a biological character requires the medicine skill. Items such as a
Gr: An item such as a ...

2019-06-13 06:52 UTC, Turtlelord26 commented on 01_01_Basic_Rules.txt
> +or stabalize a dying character. For stabalizing a dying character, see the
sp: Stabilize. Several incidences.

2019-06-13 06:52 UTC, Turtlelord26 commented on 01_01_Basic_Rules.txt
> +    Using a medkit or a repair kit to heal a wounded character takes 3 actions
Order suggestion: Using a ... to heal a wounded character in combat takes 3 Actions.

2019-06-13 06:52 UTC, Turtlelord26 commented on 01_01_Basic_Rules.txt
> +where the DC is the ammount of damage that the wound inflicted. The ammount of
Sp: Amount. 2 incidences.

2019-06-13 06:52 UTC, Turtlelord26 commented on 01_01_Basic_Rules.txt
> +skill of 10, a dex mod of 8 and rolls a 45.
Clarity point: does the targeted wound have to be declared before the roll, or can it be after? This should be stated explicitly.

2019-06-13 06:52 UTC, Turtlelord26 commented on Combat Rules/1_Combat_Rules.txt
> +stabalizing character starts stabalizing with their last action or two,
Sp: Stabilize

2019-06-13 10:56 UTC, rosebrallier commented
> Before greenlighting, I will ask you to additionally apply this nerf to relevant Doc and Engi abilities. I see class balance suffering a lot otherwise.
Perhaps the Doc and Eng abilities should take 2 actions? 3 would be incredibly punishing to their action economy, and would encompass the idea that they heal faster because they've had lots of practice.

2019-06-14 19:24 UTC, Turtlelord26 approved these changes

2019-06-14 19:25 UTC, merged