Rework of Light Dance
trowl223/Compound_X pull request #911
Opened 2019-07-26 23:07 UTC by Turtlelord26

Subject to debate.

Removed "may be used to distract..." as that can be implied (so we don't need the extra text) and players will feel better about coming up with it on their own.
Removed that enemies may roll to negate the accuracy penalty over complexity and combat slowdown concerns.

Reworded ability to clarify what "while evading enemy fire" means. Now in effect if you moved at least your move speed on your previous turn. Slight nerf, hopefully makes up for removing the save.

2019-07-30 02:38 UTC, bleehu requested changes
Requesting re-introduction of the DC 60 awareness to negate the effect; despite the added complexity, adds a nerf to the ability and a reward for aware enemies.

2019-07-30 03:22 UTC, Turtlelord26 commented
Alright, willing to test.
Awareness save or Spotting check?

2019-07-31 04:31 UTC, bleehu commented
I think we use saves to prevent something bad from happening.

2019-07-31 06:29 UTC, Turtlelord26 commented
In my reckoning, if the enemies have to roll when the ability is used (i.e. at the end of the Sea Devil's turn), then it's a save, but if the enemies have to roll when they try to attack the Sea Devil, it's a check, because they're taking action to overcome an obstacle (the hard-to-see property of their target).

It's less of a tracking headache for the DM to have the enemies roll when they attack, so they don't have to remember which enemies saw the Sea Devil light dancing.

To preserve the flatter roll distribution that saves have vs skills, it could be a straight Perception check instead.

2019-08-02 00:11 UTC, bleehu commented
That makes sense.

2019-08-03 05:47 UTC, Turtlelord26 commented
I was thinking about how to phrase the perception check, and I had an idea. What if, instead of a -1 to accuracy unless they pass a check, enemies have to pass the check to Aim at the Sea Devil?

2019-08-03 20:54 UTC, bleehu commented
Very good idea, but I'm concerned it's too powerful.

2019-08-03 22:19 UTC, Reveraine commented
I agree that looking at it now makes it look a little strong. It still has to be in low-light conditions, but perhaps adding that a being wearing IR goggles will not be confused by this?

2019-08-03 22:37 UTC, Turtlelord26 commented
I like the flavor of nonvisible light spectrum vision equipment bypassing Light Dance. I think it's acceptable mechanical complexity too.

2019-08-04 18:23 UTC, bleehu requested changes
Should there be a rate limit or action cost on trying to use perception multiple times?

2019-08-04 18:52 UTC, Turtlelord26 commented
The intention is that it's part of the Aim action. Will rephrase to make
that more obvious.

On Sun, Aug 4, 2019, 11:23 AM bleehu <notifications@github.com> wrote:

> *@bleehu* requested changes on this pull request.
>
> Should there be a rate limit or action cost on trying to use perception
> multiple times?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bleehu/Compound_X/pull/911?email_source=notifications&email_token=AFPZC3RD7X6VCSOBP7GYFZDQC4NDFA5CNFSM4IHHXOC2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCAP2H4A#pullrequestreview-270509040>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFPZC3SNYCUZXVOGCJGUAZLQC4NDFANCNFSM4IHHXOCQ>
> .
>

2019-08-04 20:54 UTC, bleehu approved these changes
Shipit!

2019-08-04 21:12 UTC, merged