added boxer step feat
trowl223/Compound_X pull request #975
Opened 2020-03-28 22:50 UTC by bleehu

modified:   CharacterCreation/03_Feats.txt

2020-03-28 22:55 UTC, bleehu commented
Issue #926

2020-03-29 06:01 UTC, Turtlelord26 requested changes
Very nice, I like this sentineloid feat.
See line items below

2020-03-29 06:01 UTC, Turtlelord26 commented on CharacterCreation/03_Feats.txt
> +*  Unarmed Training
Unarmed Combat Training

2020-03-29 06:01 UTC, Turtlelord26 commented on CharacterCreation/03_Feats.txt
> +    If an enemy tries to disengage, they must first make a Reflex save. If they
We should specify "tries to disengage ^from melee combat with you^"

2020-03-30 02:55 UTC, Turtlelord26 approved these changes

2020-03-30 03:02 UTC, merged